# Autogenerated wrapper script for Ogg_jll for x86_64-linux-gnu
export libogg

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libogg`
const libogg_splitpath = ["lib", "libogg.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libogg_path = ""

# libogg-specific global declaration
# This will be filled out by __init__()
libogg_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libogg = "libogg.so.0"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"Ogg")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list

    global libogg_path, libogg_handle
    libogg_path, libogg_handle = get_lib_path_handle!(LIBPATH_list, artifact_dir, libogg_splitpath)

    global PATH, LIBPATH
    PATH, LIBPATH = cleanup_path_libpath!(PATH_list, LIBPATH_list, ':')
    
end  # __init__()
